### ISSUE TITLE
Cannot install keytar module and weird error

### ISSUE THREAD

**Issue by demian85** [bertrandom/chrome-cookies-secure#3]
It's failing in Ubuntu 12.04 with the following error:

```
> keytar@2.0.3 install /home/demian/www/projects/iatsqueue/node_modules/chrome-cookies-secure/node_modules/keytar
> node-gyp rebuild

Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/demian/www/projects/iatsqueue/node_modules/chrome-cookies-secure/node_modules/keytar
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing keytar@2.0.3
```

What can I do?

Also I'm getting this error:

```
crypto.js:323
  var ret = this._binding.final();
                          ^
TypeError: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.Cipher.final (crypto.js:323:27)
    at decrypt (/home/demian/www/projects/iatsqueue/node_modules/chrome-cookies-secure/index.js:45:22)
    at Statement.db.each.host (/home/demian/www/projects/iatsqueue/node_modules/chrome-cookies-secure/index.js:242:21)
```

**Comment by demian85** [comment]
Ok, I ran `sudo apt-get install libgnome-keyring-dev` and it works now. But still getting the decrypt error :/

**Comment by bertrandom** [comment]
Wasn't this working before on the linux-support branch? keytar shouldn't be needed on linux because the Chrome encryption password is static.

**Comment by demian85** [comment]
I tested it on Linux Mint 17 and it worked. But it fails on Ubuntu 12.04 (at the office)
I tried changing encodings with no luck.

**Comment by bertrandom** [comment]
Hmm, that's interesting. It's kinda hard for me to replicate though, how did you install Chrome?

**Comment by demian85** [comment]
I supposed I downloaded it like a year ago and it updates daily using the
package manager. Using the stable version.

**Comment by bertrandom** [comment]
Can you try now with version 1.1.1? I found an issue with the encryption padding for certain cookies.

**Comment by demian85** [comment]
Seems to work now, thanks!

Now make it work for Firefox! :P
