### ISSUE TITLE
Decrypting some cookies results in RangeError

### ISSUE THREAD

**Issue by eloquence** [bertrandom/chrome-cookies-secure#5]
On decrypting cookies set by one particular site (Goodreads.com), I got the following error:

> RangeError: out of range index
>     at RangeError (native)
>     at decrypt (node_modules/chrome-cookies-secure/index.js:59:8)
>     at Statement.db.each.host (node_modules/chrome-cookies-secure/index.js:268:21)

The offending line 59 is `final.copy(decoded, decoded.length - 1);`. Changing it to `final.copy(decoded, decoded.length ? decoded.length - 1 : 0);` (no longer assuming that the target buffer contains data) fixed the issue for me, though I don't know if that's the best solution.

**Comment by bertrandom** [comment]
Are these the basic login cookies? Will test soon when I get a chance!

**Comment by eloquence** [comment]
Yep, this happened with the Goodreads login & standard site cookies, logging in via Facebook. Thanks for taking a look!

**Comment by rubengmurray** [comment]
This is a very old issue, but I see that the `final.copy(decoded, decoded.length - 1)` is still the same in the code base.

Here: https://github.com/bertrandom/chrome-cookies-secure/blob/8eeca6d405527327f30d95801ec048d38deaee1e/index.js#L42

It's a long-shot, but do you still have the code that can replicate this? If the buffer contains no data then I presume it's a bad entry, and all you were trying to do was skip it so that it didn't blow up everything else? 

That feels like a reasonable approach, and I can't see much downside with it.

We could probably log out a warning too if this happens.

**Comment by zcdev** [comment]
The Apple Silicon encryption fix (#68) was released in 3.0.0-beta.1 and is expected to be included in 3.0.1. Could someone confirm whether this still reproduces there?

**Comment by rubengmurray** [comment]
It is indeed included in `3.0.1` - https://github.com/bertrandom/chrome-cookies-secure/releases/tag/v3.0.1

I will try and verify this once and for all this weekend, as I now have an Apple Silicon machine.

**Comment by rubengmurray** [comment]
@zcdev It doesn't re-produce for my login on Goodreads.com. Apple Silicon, M4.

However, the OP was most definitely not using Apple Silicon when he raised this issue. 

Still, I think given this issue's age this one can be closed cc @eloquence

**Comment by rubengmurray** [comment]
Closing given inactivity, no other reports, and works on latest release.
